version: v1

license_allow_list:
  - MIT
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - 0BSD

license_deny_list:
  - GPL-2.0
  - GPL-3.0
  - LGPL-2.1
  - LGPL-3.0
  - AGPL-3.0
  - CPAL-1.0
  - EPL-1.0
  - EPL-2.0
  - EUPL-1.1
  - EUPL-1.2

vulnerability_check: true

base_ref: main

comment_summary_in_pr: always

warn_only: false

fail_on_severity: moderate

allow_dependencies_licenses:
  - MIT
  - Apache-2.0
  - BSD-2-Clause
  - BSD-3-Clause
  - ISC
  - 0BSD
  - MS-PL # Microsoft Public License (for Microsoft packages)

deny_packages:
  - name: "*"
    version_range: "< 0"
